const HabitantsTypes = {
    LIST_HABITANTS_REQUEST: "LIST_HABITANTS_REQUEST",
    LIST_HABITANTS_ERROR: "LIST_HABITANTS_ERROR",
    LIST_HABITANTS_SUCCESS: "LIST_HABITANTS_SUCCESS",
    DETAIL_HABITANT_REQUEST: "DETAIL_HABITANT_REQUEST",
    DETAIL_HABITANT_ERROR: "DETAIL_HABITANT_ERROR",
    DETAIL_HABITANT_SUCCESS: "DETAIL_HABITANT_SUCCESS",
  };
  
  export default HabitantsTypes;